server:
  port: 8700
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securite?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1765000
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true